version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQLDB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQLDB_DATABASE}
      MYSQL_USER: ${MYSQLDB_USER}
      MYSQL_PASSWORD: ${MYSQLDB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-p${MYSQLDB_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  app:
    depends_on:
      - db
    restart: on-failure
    build:
      context: ./
      dockerfile: Dockerfile
    env_file:
      - ..env
    ports:
      - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
      - $DEBUG_PORT:$DEBUG_PORT
    environment:
      SPRING_APPLICATION_JSON: >
        {"spring.datasource.url":"jdbc:mysql://db:3306/carsharing?serverTimezone=UTC&useSSL=false&allowPublicKeyRetrieval=true",
         "spring.datasource.username":"root",
         "spring.datasource.password":"${MYSQLDB_ROOT_PASSWORD}",
         "spring.jpa.hibernate.ddl-auto":"none",
         "spring.jpa.show-sql":"true",
         "spring.jpa.properties.hibernate.format_sql":"true"}
      JAVA_TOOL_OPTIONS: "-Djava.security.egd=file:/dev/./urandom"

volumes:
  mysql-data:
